version: "3.7"
services:
    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: prisma
        ports:
            - 5432:5432
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    # api:
    #     build: .
    #     env_file:
    #         - .env
    #     depends_on:
    #         - db
    #     ports:
    #         - 8000:8000
    # mongodb_container:
    #     # This image automatically creates a replica set required for transactions
    #     hostname: mongodb_container
    #     image: prismagraphql/mongo-single-replica:4.4.3-bionic
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: root
    #         MONGO_INITDB_ROOT_PASSWORD: prisma
    #     # entrypoint:
    #     #     [
    #     #         "/usr/bin/mongod",
    #     #         "--bind_ip_all",
    #     #         "--replSet",
    #     #         "rs0",
    #     #         "--journal",
    #     #         "--dbpath",
    #     #         "/data/db",
    #     #         "--enableMajorityReadConcern",
    #     #         "false",
    #     #     ]
    #     ports:
    #         - 27017:27017
    # mongo1:
    #     hostname: mongo1
    #     container_name: localmongo1
    #     image: mongo
    #     expose:
    #         - 27017
    #     ports:
    #         - 27017:27017
    #     restart: always
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: root
    #         MONGO_INITDB_ROOT_PASSWORD: prisma
    #     entrypoint:
    #         [
    #             "/usr/bin/mongod",
    #             "--bind_ip_all",
    #             "--replSet",
    #             "rs0",
    #             "--journal",
    #             "--dbpath",
    #             "/data/db",
    #             "--enableMajorityReadConcern",
    #             "false",
    #         ]
    # volumes:
    #     - <VOLUME-DIR>/mongo/data1/db:/data/db # This is where your volume will persist. e.g. VOLUME-DIR = ./volumes/mongodb
    #     - <VOLUME-DIR>/mongo/data1/configdb:/data/configdb
