---
name: "deploy"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - prod
    paths:
      - packages/apollo/**
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@147.182.168.201/api"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
